name: update-tap
on:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  update-tap:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        with:
          token: ${{ secrets.TOKEN }}
          tap: ${{ github.repository }}
          force: false
          livecheck: true
